# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd011660cb89b8d2ba4b4aae2bfdc3d064bdf6e0860e038469dace1e3a9bbc00d848bef6379dea51d6a73f4fe46309c93f4354a46aeb7630794bca6fbad0c1b

test:
  secret_key_base: 0c5708713a543e2a9f2b38af78b5a119f8b82e3d69898277ca040800498160f341b05b5fbb1f088b45a8cb37d6cc234e49873c68df0820e158c1061f0dd955a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
